apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linuxtips
  name: linuxtips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linuxtips
  template:
    metadata:
      labels:
        app: linuxtips
    spec:
      containers:
      - image: herijr/docker-node-linuxtips
        name: docker-node-linuxtips
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: linuxtips
  name: linuxtips-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: linuxtips
  type: NodePort
